import { Geist, Geist_Mono } from "next/font/google";
import ClientLayout from "./client-layout";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Orchid",
  description: "Generated by Orchid",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ lang: string }>; // ✅ as per docs
}) {
  const resolvedParams = await params; // ✅ await Promise
  const lang = resolvedParams.lang === "ar" ? "ar" : "en"; // ✅ cast literal
  const dir = lang === "ar" ? "rtl" : "ltr";

  return (
    <html lang={lang} dir={dir}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClientLayout 
          lang={lang}
          geistSans={geistSans}
          geistMono={geistMono}
        >
          {children}
        </ClientLayout>
      </body>
    </html>
  );
}